# Generated by Django 2.2.6 on 2019-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_auto_20191025_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogoal",
            name="permalink",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
