# Generated by Django 2.2.6 on 2019-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0005_match_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
