# Generated by Django 2.2.6 on 2019-11-12 14:22

import django.db.models.deletion
from django.db import migrations, models

from matches.models import Match, Team


def link_teams(apps, schema_editor):
    # only applicable to one migration
    # # print(f'Starting to link teams')
    # # teams = list()
    # # for match in Match.objects.all():
    # #     teams.append(match.home_team)
    # #     teams.append(match.away_team)
    # # teams = list(set(teams))
    # # print(f'Teams in database: {len(teams)}')
    # # i = 9990000
    # # for team in teams:
    # #     print(f'Creating: {team}')
    # #     Team.objects.create(name=team, id=i)
    # #     i += 1
    # # for match in Match.objects.all():
    # #     print(f'Linking match: {match.home_team} - {match.away_team}')
    # #     home_team = Team.objects.get(name=match.home_team)
    # #     away_team = Team.objects.get(name=match.away_team)
    # #     match.home_team_link = home_team
    # #     match.away_team_link = away_team
    # #     match.save()
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('matches', '0006_auto_20191108_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('logo', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='videogoal',
            name='permalink',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team',
                                    to='matches.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team',
                                    to='matches.Team'),
        ),
        migrations.RunPython(link_teams),
    ]
