# Generated by Django 2.2.6 on 2019-11-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0006_auto_20191108_1625"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=256)),
                ("logo", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="videogoal",
            name="permalink",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_team_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_team",
                to="matches.Team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_team",
                to="matches.Team",
            ),
        ),
    ]
