# Generated by Django 2.2.6 on 2019-11-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20191112_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
    ]
