# Generated by Django 2.2.8 on 2020-01-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0010_teamalias"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="logo",
            new_name="logo_url",
        ),
    ]
