# Generated by Django 2.2.8 on 2020-01-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0013_auto_20200128_1725"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="logo_file",
            field=models.ImageField(default=None, upload_to="logos"),
        ),
    ]
