# Generated by Django 3.0.3 on 2020-02-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0016_videogoalmirror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogoalmirror",
            name="videogoal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mirrors",
                to="matches.VideoGoal",
            ),
        ),
    ]
