# Generated by Django 3.0.3 on 2020-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_auto_20200207_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_file',
            field=models.ImageField(default=None, null=True, upload_to='logos'),
        ),
    ]
