# Generated by Django 3.0.3 on 2020-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_auto_20200213_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
