# Generated by Django 3.0.3 on 2020-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_team_name_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tweet_sent',
            field=models.BooleanField(default=False),
        ),
    ]
