# Generated by Django 3.0.3 on 2020-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0021_auto_20200301_2142"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordWebhookUrl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100, unique=True)),
                ("webhook", models.CharField(max_length=2000, unique=True)),
            ],
        ),
    ]
