# Generated by Django 3.0.3 on 2020-03-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0022_discordwebhookurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordwebhookurl",
            name="message",
            field=models.CharField(default="", max_length=2000),
            preserve_default=False,
        ),
    ]
