# Generated by Django 3.0.3 on 2020-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0025_delete_webhookurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="tweet_sent",
            new_name="msg_sent",
        ),
    ]
