# Generated by Django 3.0.3 on 2020-03-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0026_auto_20200304_1152"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("priority", models.IntegerField()),
                ("name", models.CharField(default=None, max_length=256, null=True)),
                ("slug", models.CharField(default=None, max_length=256, null=True)),
                ("flag", models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(default=None, max_length=256, null=True)),
                ("slug", models.CharField(default=None, max_length=256, null=True)),
                ("year", models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("unique_id", models.IntegerField()),
                ("name", models.CharField(default=None, max_length=256, null=True)),
                ("slug", models.CharField(default=None, max_length=256, null=True)),
                (
                    "unique_name",
                    models.CharField(default=None, max_length=256, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="matches.Category",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="season",
                to="matches.Season",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament",
                to="matches.Tournament",
            ),
        ),
    ]
