# Generated by Django 3.0.3 on 2020-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0028_auto_20200304_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='uid',
        ),
        migrations.AddField(
            model_name='tournament',
            name='unique_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
