# Generated by Django 3.0.3 on 2020-03-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0032_auto_20200306_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="matches.Category",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_category",
                to="matches.Category",
            ),
        ),
    ]
