# Generated by Django 3.0.3 on 2020-03-09 15:11

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0033_auto_20200308_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogoal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videogoal",
            name="next_mirrors_check",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
