# Generated by Django 3.1 on 2020-08-07 13:56

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def migrate_data_forward(apps: list, schema_editor: BaseDatabaseSchemaEditor) -> None:
    # for instance in Team.objects.all().order_by('id'):
    #     print(f"Generating slug for team {instance} (id: {instance.id})")
    #     instance.save()  # Will trigger slug update
    pass


def migrate_data_backward(apps: list, schema_editor: BaseDatabaseSchemaEditor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0034_auto_20200309_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(default="to-replace", max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
