# Generated by Django 3.1 on 2020-08-07 13:56

from django.db import migrations, models

from matches.models import Team


def migrate_data_forward(apps, schema_editor):
    for instance in Team.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('matches', '0034_auto_20200309_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='to-replace', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
