# Generated by Django 3.1 on 2020-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0035_team_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
