# Generated by Django 3.1 on 2020-10-12 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0040_team_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
