# Generated by Django 3.1.5 on 2021-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0041_team_logo_updated_at'),
    ]

    operations = [
        migrations.RunSQL('''
        DELETE FROM matches_teamalias del
        USING ( SELECT id, row_number() over(partition by alias, team_id order by id desc) as rn
                FROM matches_teamalias
        ) sub
        WHERE sub.id = del.id
        AND sub.rn > 1;'''),
        migrations.AddConstraint(
            model_name='teamalias',
            constraint=models.UniqueConstraint(fields=('alias', 'team'), name='unique_team_alias'),
        ),
    ]
