# Generated by Django 3.2.9 on 2021-11-06 19:46

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0045_match_matches_mat_datetim_e89d1a_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='team_name_ln_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='teamalias',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('alias'), name='gin_trgm_ops'), name='team_alias_ln_gin_idx'),
        ),
    ]
