# Generated by Django 3.2.9 on 2021-11-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0046_auto_20211106_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=1024, unique=True)),
                ('fetched', models.DateTimeField(auto_now_add=True)),
                ('videogoal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_match', to='matches.videogoal')),
            ],
        ),
        migrations.AddIndex(
            model_name='postmatch',
            index=models.Index(fields=['permalink'], name='matches_pos_permali_1d511d_idx'),
        ),
    ]
