# Generated by Django 3.2.9 on 2021-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0047_auto_20211107_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogoal',
            name='permalink',
        ),
        migrations.AddField(
            model_name='postmatch',
            name='away_team_str',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='postmatch',
            name='home_team_str',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='postmatch',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
