# Generated by Django 3.2.10 on 2021-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0049_videogoal_auto_moderator_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_video_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
