# Generated by Django 3.2.10 on 2021-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0050_match_first_video_datetime"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["first_video_datetime"], name="matches_mat_first_v_9623a2_idx"
            ),
        ),
    ]
