# Generated by Django 4.1.3 on 2022-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0055_alter_videogoal_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="last_sent_tweet",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
