# Generated by Django 4.1.3 on 2022-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0056_match_last_sent_tweet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="last_sent_tweet",
            new_name="last_tweet_time",
        ),
        migrations.AddField(
            model_name="match",
            name="last_tweet_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
