# Generated by Django 4.2.4 on 2023-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0058_tweetsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetsent",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
