# Generated by Django 5.0.4 on 2024-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0060_delete_tweetsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="short_name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
