# Generated by Django 5.0.4 on 2024-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0061_team_short_name"),
    ]

    operations = [
        migrations.RunSQL("UPDATE matches_team SET short_name = name;"),
    ]
