# Generated by Django 5.0.4 on 2024-04-15 14:31

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0062_auto_20240415_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="short_name",
            field=models.CharField(default="to-update", max_length=256),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="team",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("short_name"), name="gin_trgm_ops"
                ),
                name="team_short_name_ln_gin_idx",
            ),
        ),
    ]
