# Generated by Django 5.0.7 on 2024-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0063_alter_team_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogoal",
            name="source",
            field=models.IntegerField(choices=[(1, "soccer"), (2, "footballhighlights")], default=1),
        ),
    ]
