# Generated by Django 5.0.7 on 2024-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0064_videogoal_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogoal",
            name="link_title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
