# Generated by Django 4.0.2 on 2022-02-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0051_match_matches_mat_first_v_9623a2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfricaMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='africa_match', to='matches.match')),
            ],
            options={
                'db_table': 'africa_match',
            },
        ),
    ]
