# Generated by Django 4.1.2 on 2022-10-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africa", "0003_remove_africamatchesfilter_exclude_teams_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="africamatchesfilter",
            name="exclude_categories",
        ),
        migrations.RemoveField(
            model_name="africamatchesfilter",
            name="exclude_tournaments",
        ),
        migrations.RemoveField(
            model_name="africamatchesfilter",
            name="include_categories",
        ),
        migrations.RemoveField(
            model_name="africamatchesfilter",
            name="include_tournaments",
        ),
        migrations.DeleteModel(
            name="AfricaMatch",
        ),
        migrations.DeleteModel(
            name="AfricaMatchesFilter",
        ),
    ]
