# Generated by Django 3.0.3 on 2020-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("consumer_key", models.CharField(max_length=100, unique=True)),
                ("consumer_secret", models.CharField(max_length=100, unique=True)),
                ("access_token_key", models.CharField(max_length=100, unique=True)),
                ("access_token_secret", models.CharField(max_length=100, unique=True)),
                ("message", models.CharField(max_length=2000)),
            ],
        ),
    ]
