# Generated by Django 3.0.3 on 2020-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_events", "0008_auto_20200304_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="event_type",
            field=models.IntegerField(
                choices=[(1, "Match"), (2, "Video"), (3, "Mirror")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_type",
            field=models.IntegerField(
                choices=[(1, "Match"), (2, "Video"), (3, "Mirror")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="webhook_url",
            field=models.CharField(max_length=2000),
        ),
    ]
