# Generated by Django 3.2 on 2021-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_events", "0012_auto_20200924_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
