# Generated by Django 3.2 on 2021-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_events", "0013_auto_20210410_1529"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=2000)),
                ("result", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhooks",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="custommessage_webhooks",
                        to="msg_events.Webhook",
                    ),
                ),
            ],
        ),
    ]
