# Generated by Django 3.2 on 2021-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_events', '0015_alter_custommessage_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
