# Generated by Django 4.0.2 on 2022-02-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0051_match_matches_mat_first_v_9623a2_idx'),
        ('msg_events', '0020_auto_20211108_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='webhooks',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_webhooks', to='msg_events.Webhook'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='exclude_categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_exclude_categories', to='matches.Category'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='exclude_teams',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_exclude_teams', to='matches.Category'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='exclude_tournaments',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_exclude_tournaments', to='matches.Tournament'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='include_categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_include_categories', to='matches.Category'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='include_teams',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_include_teams', to='matches.Team'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='include_tournaments',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_include_tournaments', to='matches.Tournament'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='exclude_categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_exclude_categories', to='matches.Category'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='exclude_teams',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_exclude_teams', to='matches.Category'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='exclude_tournaments',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_exclude_tournaments', to='matches.Tournament'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='include_categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_include_categories', to='matches.Category'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='include_teams',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_include_teams', to='matches.Team'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='include_tournaments',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_include_tournaments', to='matches.Tournament'),
        ),
    ]
