# Generated by Django 4.0.2 on 2022-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_events', '0021_alter_custommessage_webhooks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'MatchFirstVideo'), (2, 'Video'), (3, 'Mirror'), (4, 'MatchHighlights'), (5, 'MatchScoreChanged'), (6, 'MatchResult')], default=1),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'MatchFirstVideo'), (2, 'Video'), (3, 'Mirror'), (4, 'MatchHighlights'), (5, 'MatchScoreChanged'), (6, 'MatchResult')], default=1),
        ),
    ]
