# Generated by Django 4.1.3 on 2022-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_events", "0022_alter_tweet_event_type_alter_webhook_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (1, "MatchFirstVideo"),
                    (2, "Video"),
                    (3, "Mirror"),
                    (4, "MatchHighlights"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (1, "MatchFirstVideo"),
                    (2, "Video"),
                    (3, "Mirror"),
                    (4, "MatchHighlights"),
                ],
                default=1,
            ),
        ),
    ]
