# Generated by Django 4.2.1 on 2023-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_events", "0023_alter_tweet_event_type_alter_webhook_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommessage",
            name="tweets",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="%(class)s_tweets", to="msg_events.webhook"
            ),
        ),
    ]
