# Generated by Django 4.2.1 on 2023-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_events", "0024_custommessage_tweets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommessage",
            name="tweets",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="%(class)s_tweets", to="msg_events.tweet"
            ),
        ),
    ]
