# Generated by Django 4.2.4 on 2023-08-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg_events", "0026_alter_custommessage_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="destination",
            field=models.IntegerField(choices=[(1, "Discord"), (2, "Slack"), (3, "IFTTT")], default=1),
        ),
    ]
