# Generated by Django 5.0.7 on 2024-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_events", "0027_alter_webhook_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="source",
            field=models.IntegerField(choices=[(1, "soccer"), (2, "footballhighlights")], default=1),
        ),
        migrations.AddField(
            model_name="webhook",
            name="source",
            field=models.IntegerField(choices=[(1, "soccer"), (2, "footballhighlights")], default=1),
        ),
    ]
