# Generated by Django 3.0.3 on 2020-03-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNotFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=1024, unique=True)),
                ('url', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('home_team_str', models.CharField(max_length=256)),
                ('away_team_str', models.CharField(max_length=256)),
            ],
        ),
    ]
