# Generated by Django 3.0.3 on 2020-03-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchnotfound",
            name="url",
        ),
    ]
