# Generated by Django 3.0.3 on 2020-03-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitoringaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringaccount',
            old_name='telegram_user_ud',
            new_name='telegram_user_id',
        ),
    ]
