# Generated by Django 3.2.9 on 2021-11-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20210410_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchNotFound',
        ),
    ]
