# Generated by Django 4.1.3 on 2022-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0008_alter_performancemonitorevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringaccount",
            name="goals_heartbeat_url",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="monitoringaccount",
            name="matches_heartbeat_url",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
