# Generated by Django 4.1.3 on 2022-11-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0009_monitoringaccount_goals_heartbeat_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerformanceMonitorEvent",
        ),
    ]
