# Generated by Django 4.1.7 on 2023-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0010_delete_performancemonitorevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringaccount",
            name="goals_reddit_heartbeat_url",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
