# Generated by Django 5.0.4 on 2024-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0011_monitoringaccount_goals_reddit_heartbeat_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringaccount",
            name="telegram_alert_bot_key",
            field=models.CharField(default="empty", max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
