# Generated by Django 5.0.4 on 2024-04-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0012_monitoringaccount_telegram_alert_bot_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringaccount",
            name="proxy_heartbeat",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
