# Generated by Django 3.1.7 on 2021-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('regex_home_team', models.CharField(default=None, max_length=256, null=True)),
                ('regex_away_team', models.CharField(default=None, max_length=256, null=True)),
                ('ner_home_team', models.CharField(default=None, max_length=256, null=True)),
                ('ner_away_team', models.CharField(default=None, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
