# Generated by Django 3.1.7 on 2021-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nerlog",
            name="ner_away_team",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="nerlog",
            name="ner_home_team",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="nerlog",
            name="regex_away_team",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="nerlog",
            name="regex_home_team",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
